// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-campaigns.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supa(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_campaigns_default = defineTool({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List the signed-in user's WineExporters campaigns, most recent first.",
  inputSchema: {
    status: z.string().optional().describe("Filter by campaign status (e.g. 'draft', 'launched', 'pending_validation')."),
    limit: z.number().int().min(1).max(100).default(20).describe("Max number of campaigns to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supa(ctx).from("campaigns").select("id, name, status, target_markets, created_at, launched_at, audience_estimate, stats_opens, stats_clicks, stats_replies").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supa2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "List CRM leads",
  description: "List the signed-in user's CRM leads, optionally filtered by status or campaign.",
  inputSchema: {
    status: z2.string().optional().describe("Filter by lead status (e.g. 'new', 'contacted', 'qualified', 'won', 'lost')."),
    campaign_id: z2.string().uuid().optional().describe("Filter by campaign UUID."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Max number of leads to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, campaign_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supa2(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (campaign_id) q = q.eq("campaign_id", campaign_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supa3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool3({
  name: "update_lead_status",
  title: "Update lead status",
  description: "Update the status of a CRM lead (e.g. move it to 'contacted', 'qualified', 'won', 'lost').",
  inputSchema: {
    lead_id: z3.string().uuid().describe("UUID of the lead to update."),
    status: z3.string().min(1).describe("New status value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supa3(ctx).from("leads").update({ status }).eq("id", lead_id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead ${lead_id} updated to ${status}.` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/append-lead-note.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supa4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var append_lead_note_default = defineTool4({
  name: "append_lead_note",
  title: "Append note to lead",
  description: "Append a timestamped note to a CRM lead's owner_notes.",
  inputSchema: {
    lead_id: z4.string().uuid().describe("UUID of the lead."),
    note: z4.string().min(1).describe("Note text to append.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ lead_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supa4(ctx);
    const { data: existing, error: readErr } = await client.from("leads").select("owner_notes").eq("id", lead_id).single();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    const stamp = (/* @__PURE__ */ new Date()).toISOString();
    const prefix = existing?.owner_notes ? `${existing.owner_notes}

` : "";
    const next = `${prefix}[${stamp}] ${note}`;
    const { data, error } = await client.from("leads").update({ owner_notes: next }).eq("id", lead_id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Note appended." }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dmgafmigqfycyaopdviw";
var mcp_default = defineMcp({
  name: "wineexporters-mcp",
  title: "WineExporters",
  version: "0.1.0",
  instructions: "Tools to browse WineExporters campaigns and manage CRM leads for the signed-in user. Use list_campaigns and list_leads to explore, update_lead_status to move leads in the pipeline, and append_lead_note to record activity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_campaigns_default, list_leads_default, update_lead_status_default, append_lead_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
